databaseUrl: postgres://postgres:postgres@localhost:5432/bahngleise?sslmode=disable
overpassUrl: https://overpass-api.de/api/interpreter
countries:
  - iso: DE
    name: Germany
    area: Deutschland
