databaseUrl: postgres://postgres:postgres@localhost:5432/bahngleise?sslmode=disable
overpassUrl: https://overpass-api.de/api/interpreter
countries:
  # - iso: CH
  #   name: Switzerland
  #   url: http://localhost:8100/switzerland-latest.osm.pbf
  - iso: DE
    name: Germany
    area: Deutschland
  # - iso: FR
  #   name: France
  #   url: http://localhost:8100/france-latest.osm.pbf
